"""init

Revision ID: b7ec73e0b7ce
Revises: 
Create Date: 2021-09-07 02:17:11.456527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ec73e0b7ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_model',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_unique_name_bike_model', 'bike_model', ['name'], unique=True, postgresql_where=sa.text('NOT is_deleted'))
    op.create_table('licence_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transmission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('mobile_number', sa.Text(), nullable=True),
    sa.Column('nric_number', sa.Text(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('licence_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['licence_class_id'], ['licence_class.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bike',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('storage_rack', sa.Boolean(), nullable=True),
    sa.Column('storage_box', sa.Boolean(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('rate_unit', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('images', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('licence_class_id', sa.Integer(), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['licence_class_id'], ['licence_class.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['bike_model.id'], ),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_model_id'), 'bike', ['model_id'], unique=False)
    op.create_table('bike_availability',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bike_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['bike_id'], ['bike.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bike_availability')
    op.drop_index(op.f('ix_bike_model_id'), table_name='bike')
    op.drop_table('bike')
    op.drop_table('user')
    op.drop_table('transmission')
    op.drop_table('licence_class')
    op.drop_index('ix_unique_name_bike_model', table_name='bike_model', postgresql_where=sa.text('NOT is_deleted'))
    op.drop_table('bike_model')
    # ### end Alembic commands ###
