"""add_bike_availabilities

Revision ID: 1435b933a01f
Revises: f1dcba966fec
Create Date: 2021-08-10 01:15:30.097408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1435b933a01f'
down_revision = 'f1dcba966fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_availability',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bike_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['bike_id'], ['bike.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bike_availability')
    # ### end Alembic commands ###
