"""add_bike

Revision ID: 878abf4e7a15
Revises: bc5e75feb0ff
Create Date: 2021-07-31 22:01:11.152215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '878abf4e7a15'
down_revision = 'bc5e75feb0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model', sa.Integer(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('required_licence', postgresql.ENUM('2', '2A', '2B', name='drivinglicencetypeenum', create_type=False), nullable=True),
    sa.Column('transmission', sa.Text(), nullable=True),
    sa.Column('storage_box', sa.Boolean(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('rate_unit', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('images', sa.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bike')
    # ### end Alembic commands ###
