"""add_bike

Revision ID: 6e4827ce792f
Revises: bc5e75feb0ff
Create Date: 2021-08-01 16:56:07.486041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e4827ce792f'
down_revision = 'bc5e75feb0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_model',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bike',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('required_licence', postgresql.ENUM('2', '2A', '2B', name='drivinglicencetypeenum', create_type=False), nullable=True),
    sa.Column('transmission', sa.Text(), nullable=True),
    sa.Column('storage_box', sa.Boolean(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('rate_unit', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('images', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['bike_model.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_model_id'), 'bike', ['model_id'], unique=False)
    op.alter_column('user', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_bike_model_id'), table_name='bike')
    op.drop_table('bike')
    op.drop_table('bike_model')
    # ### end Alembic commands ###
