"""init

Revision ID: e3ae4222ce98
Revises: 
Create Date: 2021-09-04 02:22:04.343381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3ae4222ce98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_model',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_unique_name_bike_model', 'bike_model', ['name'], unique=True, postgresql_where=sa.text("is_deleted=False"))
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('mobile_number', sa.Text(), nullable=True),
    sa.Column('nric_number', sa.Text(), nullable=True),
    sa.Column('driving_licence_type', postgresql.ENUM('2', '2A', '2B', name='drivinglicencetypeenum'), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bike',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('required_licence', postgresql.ENUM('2', '2A', '2B', name='drivinglicencetypeenum', create_type=False), nullable=True),
    sa.Column('transmission', postgresql.ENUM('Manual', 'Automatic', name='transmissiontypeenum'), nullable=True),
    sa.Column('storage_box', sa.Boolean(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('rate_unit', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('images', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['bike_model.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_model_id'), 'bike', ['model_id'], unique=False)
    op.create_table('bike_availability',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bike_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['bike_id'], ['bike.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bike_availability')
    op.drop_index(op.f('ix_bike_model_id'), table_name='bike')
    op.drop_table('bike')
    op.drop_table('user')
    op.drop_index('ix_unique_name_bike_model', table_name='bike_model', postgresql_where=sa.text('"is_deleted=False"'))
    op.drop_table('bike_model')
    op.execute("DROP TYPE drivinglicencetypeenum;")
    op.execute("DROP TYPE transmissiontypeenum;")
    # ### end Alembic commands ###
